DyspBackend/DyspBackend/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from DyspBackend import views

urlpatterns = [

    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls')), 
    url(r'^about/', include('about.urls')),
    
    url(r'^question/',include('questions.urls')),
    url(r'^user/', include('users.urls')),


    #url(r'^settings', include('settings.urls')),
    
]

DyspBackend/about/urls.py
from django.conf.urls import include, url
from . import views


urlpatterns = [

	url(r'^$', views.about, name='about'),
]

DyspBackend/accounts/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from accounts import views
from django.contrib.auth.views import login, logout

urlpatterns = [

	url(r'^$', views.home),
	url(r'^login/$', login, {'template_name': 'accounts/login.html'}),
	url(r'^logout/$', logout, {'template_name': 'accounts/logout.html'}),
	url(r'^register/$', views.register, name='register'),
	url(r'^profile/$',views.profile, name='profile'),
	url(r'^settings/$',views.settings, name='settings'),
]

DyspBackend/questions/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'question'


urlpatterns = [
	#/question/
	url(r'^$', views.index, name='index'),

	#/question/12/
	url(r'^(?P<q_id>[0-9]+)/$', views.qs, name='qs'),

	#/register/??
    #url(r'^register/$', views.UserFormView.as_view(), name='register'),

    #/question/q/add/
    url(r'q/add/$', views.QuestionCreate.as_view(), name='question-add'),



]

DyspBackend/users/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
	#user/1
	url(r'^(?P<user_id>[0-9]+)/$', views.us, name='us' )

]

DyspBackend/about/models.py
from django.db import models

# Create your models here.

DyspBackend/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.
class UserProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	bio = models.CharField(max_length=100, default='')
	city = models.CharField(max_length=100, default='')
	phone = models.IntegerField(default=0)

def create_profile(sender, **kwargs):
	if kwargs['created']:
		user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

DyspBackend/questions/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    contact_no = models.CharField(max_length=13)

    #def __str__(self):
     #   return self.first_name +"- "+ self.last_name

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

class Question(models.Model):
    question = models.CharField(max_length=100)
    creator = models.CharField(max_length=50)
    views = models.BigIntegerField
    report = models.IntegerField
    no_answers = models.IntegerField
    tags = models.CommaSeparatedIntegerField
    #date = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.question +"- "+ self.creator


class Answer(models.Model):
    answer = models.CharField(max_length=500)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.CharField(max_length=50)
    upvotes = models.IntegerField
    views = models.BigIntegerField
    report = models.IntegerField
    #date = models.DateTimeField(auto_now = True)
    
    def __str__(self):
        return self.answer +"- "+ str(self.upvotes)

DyspBackend/settings/models.py
from django.db import models
from questions.models import Profile, Question, Answer

DyspBackend/users/models.py
from django.db import models
from datetime import datetime
from questions.models import Profile, Question, Answer

#d = {1:'Technology', 2:'Science', 3: 'History', 4:'Music', 5:'Cooking', 6:'Health', 7:'Food', 8:'Baking', 9:'Start Ups'}
# Create your models here.

DyspBackend/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class RegistrationForm(UserCreationForm):
	email=forms.EmailField(required=True)

	class Meta:
		model = User
		fields=(
			'username',
			'first_name',
			'last_name',
			'email',
			'password1',
			'password2',
		)
	def save(self, commit=True):
		user= super(RegistrationForm, self).save(commit=False)
		user.first_name=self.cleaned_data['first_name']
		user.last_name=self.cleaned_data['last_name']
		user.email=self.cleaned_data['email']

		if commit:
			user.save()

		return user

class EditProfileForm(UserChangeForm):

	class Meta:
		model = User
		fields=(
			'first_name',
			'last_name',
			'email',
		)

DyspBackend/questions/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

DyspBackend/DyspBackend/views.py
from django.shortcuts import redirect

def login_redirect(request):
	return redirect('/account/login')

DyspBackend/about/views.py
from django.shortcuts import render

# Create your views here.
def about(request):
	return render(request, 'about/about.html')

DyspBackend/accounts/views.py
from django.shortcuts import render, redirect
from accounts.forms import RegistrationForm, EditProfileForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm

# Create your views here.
def home(request):
	return render(request, 'accounts/home.html')

def register(request):
	if request.method == 'POST':
		form = RegistrationForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/account')
	else:
		form = RegistrationForm()

		args = {'form': form}
	return render(request, 'accounts/reg_form.html', args)

def profile(request):
	args = {'user': request.user}
	return render(request, 'accounts/profile.html', args)

def settings(request):
	if request.method =='POST':
		form = EditProfileForm(request.POST, instance = request.user)

		if form.is_valid:
			form.save()
			return redirect('/account/profile')

	else:
		form = EditProfileForm(instance = request.user)
		args = {'form': form}
		return render(request, 'accounts/settings.html', args)

DyspBackend/questions/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from django.http import HttpResponse
from .models import Question, Answer
from .forms import UserForm
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy





def index(request):
	all_qs = Question.objects.all()
	context = {'all_qs':all_qs}
	return render(request, 'questions/index.html',context)

def qs(request, q_id):
	try:
		q = Question.objects.get(pk=q_id)
		ans = Answer.objects.get(question=q_id)

	except Question.DoesNotExist:
		raise Http404("Question does not exist!")

	return render(request, 'questions/qs.html',{'q':q, 'ans':ans})


class QuestionCreate(CreateView):
	model = Question
	fields = ['question', 'creator']

#class QuestionUpdate(UpdateView):
#	model = Question
#	fields = ['question', 'creator']
	

DyspBackend/settings/views.py
from django.shortcuts import render

# Create your views here.

DyspBackend/users/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Profile

def us(request, user_id):
	try:
		u = Profile.objects.get(pk=user_id)
	except UserInfo.DoesNotExist:
		raise Http404("User does not exist! ")
	return render(request, 'users/us.html', {'u' : u})

DyspBackend/accounts/templates/accounts/home.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    <title>Home | Dyspodium</title>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    
    <link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/all-themes.css' %}" rel="stylesheet">
    
</head>
<body class="theme-red" style="background-color:#2E2E2E;">

    <div class="overlay"></div>
   <nav class="navbar" style="background-color:#04B486; color:#2E2E2E;">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="index.html"><b>DYSPODIUM</b></a>
            </div>
            <form class="navbar-form navbar-left" action="#" method="get" role="search">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search" name="q" value="">
                        <div class="input-group-btn">
                            <button class="btn btn-default glyphicon glyphicon-search" type="submit"></button>
                        </div>
                </div>
            </form>
            <div class="collapse navbar-collapse" id="navbar-collapse" style="background-color:#04B486; color:#2E2E2E;" >

                <ul class="nav navbar-nav navbar-right">
                   
                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Add Question</span>
                        </a>
                    </li>

                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-bell" aria-hidden="true"></span></span>
                        </a>
                    </li>
                   
                    
                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></span>
                        </a>
                    </li>
                    
    
        <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span></span>
                        </a>
                    </li>
        <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span></span>
                        </a>
                    </li>

           
                    </ul>
            </div>
        </div>
    </nav>
    <section class="content" style="background-color:#2E2E2E; color:#04B486;">
        <div class="container-fluid">
            <div class="block-header">
                <h3><font size="6">User Feed</font></h3>
            </div>
            <div class="container-fluid">

                    {% for i in all_qs %}
                     <div class="card" style="background-color:#424242; color:#04B486;">
                        <div class="row">
                        <div class="col-sm-1" ><img src="{% static 'images/user.png' %}" width="35" height="35" alt="User" class="img-circle img-responsive" /></div>
                        <div class="col-sm-8" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><h5><a href = "/question/{{i.id}}/"  style="color:red"><h5> <font size="3"> {{ i.creator }} </font> <font size="5"> {{i.question}} </a> </font></h5></div>
                        <div class="col-sm-3" ><div align="right"><h6><font size="2">Report</font></h6></div>
                                           <div align="right"><h6><font size="2">Date</font></h6></div></div>
                          </div>
                        </div>  
                    {% endfor %}
                    </div>
                    </div>
        </section>     
        </body>
</html>

DyspBackend/accounts/templates/accounts/home1.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="(% static 'lc.css' %}">
<script type="text/javascript" src="{% static 'lj.js' %}"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<title>Home</title>
</head>
<body>
Hello!
</body>
</html>

DyspBackend/accounts/templates/accounts/login.html
{% load staticfiles %}

<html>
<head>
	<link rel="stylesheet" href="{% static 'lc.css' %}">
<script type="text/javascript" src="{% static 'lj.js' %}"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<title>Login</title>
</head>
<body>
	<div class="login-page">
  		<div class="form">
    		<form class="login-form" method="post">
			<h1 >Welcome!</h1> 
				<p > You can login here.</p>
	
				{% csrf_token %}
				{{ form.as_p }}

				<button type="submit">Login</button>

				<p class="message">Not registered? <a href="/account/register/">Create an account</a></p>
			</form>
			<div>
				<pre><a href="/about">About</a>   <a href="/contact_us">Contact Us</a>   <a href="/team">Team</a></pre>
			</div>
  		</div>
	</div>	
</body>
</html>

DyspBackend/accounts/templates/accounts/login2.html
{% load staticfiles %}
<head>
<link rel="stylesheet" href="{% static 'lc.css' %}">
<script type="text/javascript" src="{% static 'lj.js' %}"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<div class="login-page">
  <div class="form">
    <form class="login-form">
      <input type="text" placeholder="username"/>
      <input type="password" placeholder="password"/>
      <button>login</button>
      <p class="message">Not registered? <a href="signup.html">Create an account</a></p>
    </form>
  </div>
</div>

DyspBackend/accounts/templates/accounts/logout.html
{% load staticfiles %}

<html>
<head>
	<link rel="stylesheet" href="% static 'lc.css' %}">
<script type="text/javascript" src="% static 'lj.js' %}"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<title>Login</title>
</head>
<body>
	<h1>Logged Out!</h1> 
	<p>You have logeed out.</p>
	<p>Not Registered?</p>
	<button><a href="/account/register/">Register</a></button>
</body>
</html>

DyspBackend/accounts/templates/accounts/profile.html
{% load staticfiles %}
<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>Profile</title>
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link href= "{% static 'bootstrap/css/bootstrap.css' %}"" rel="stylesheet">
    <link href="{% static 'css/all-themes.css' %}" rel="stylesheet" />
</head>
<body class="theme-red" style="background-color:#2E2E2E;">
 <div class="overlay"></div>
   <nav class="navbar" style="background-color:#04B486; color:#2E2E2E;">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="index.html"><b>DYSPODIUM</b></a>
            </div>
            <form class="navbar-form navbar-left" action="#" method="get" role="search">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search" name="q" value="">
                        <div class="input-group-btn">
                            <button class="btn btn-default glyphicon glyphicon-search" type="submit"></button>
                        </div>
                </div>
            </form>
            <div class="collapse navbar-collapse" id="navbar-collapse" style="background-color:#04B486; color:#2E2E2E;" >

                <ul class="nav navbar-nav navbar-right">
                   
                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Add Question</span>
                        </a>
                    </li>

                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-bell" aria-hidden="true"></span></span>
                        </a>
                    </li>
                   
                    
                    <li class="">
                        <a href="/account/settings">
                            <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></span>
                        </a>
                    </li>
                    
        <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span></span>
                        </a>
                    </li>
        <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span></span>
                        </a>
                    </li>
                    </ul>
            </div>
        </div>
    </nav>
    <div class="overlay"></div>
   <nav class="navbar" style="background-color:#04B486; color:#2E2E2E;">
        <div class="container-fluid">
            <div class="navbar-header">
                
				<div class="col-md-3 image">
										
                                        <img src="{% static 'images/user.png' %}" width="700" height="1000" alt="User" class="img-circle img-responsive" hspace = "" />
                                        <div>
										<b>{{user.first_name}} {{user.last_name}}<br> ({{user}})<br> {{user.email}}</b>
										
            </div>
            
                        </div>
                </div>
            <div class="collapse navbar-collapse" id="navbar-collapse" style="background-color:#04B486; color:#2E2E2E;" >

                    
    
            </div>
        </div>
    </nav>
	<nav class="navbar" style="background-color:#04B486; color:#2E2E2E;">
		<ul class="nav navbar-nav navbar-left">
                   
                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>ANSWERS</span>
                        </a>
                    </li>
		</ul>
		<ul class="nav navbar-nav navbar-middle">
                   
                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>QUESTIONS</span>
                        </a>
                    </li>
		</ul>
		<ul class="nav navbar-nav navbar-left">
                   
                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>INTEREST</span>
                        </a>
                    </li>
		</ul>
	</nav>
   

    <section class="content" style="background-color:#2E2E2E; color:#04B486;">
     <section class="content" style="background-color:#2E2E2E; color:#04B486;">
        <div class="container-fluid">
            <div class="block-header">
                <h6></h6>
            </div>
            <div class="row clearfix" >
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="card" style="background-color:#424242; color:#04B486;">
                        <div class="header" style="background-color:##424242; color:#04B486;">

                            <div class="row clearfix">
                                <div class="col-xs-12 col-sm-6">
                                    <div class="user-info">
                                       

                                         <div class="info-container" style="background-color:#424242; color:#04B486;">
                                            <div class="name row clearfixl" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" align = "right" height = "1000"><h5> {{user.bio}} </h5></div>
                                        </div>
                                        </div>
                                            <div class="col-xs-12 col-sm-6 align-right" >
                                                <div class="switch panel-switch-btn">  
                                                </div>
                                                </div>
                                            </div>

                                    
                                           
                                    <div class="col-xs-12 col-sm-6">
                                   
                                            <div class="col-xs-12 col-sm-6 align-right" >
                                                <div class="switch panel-switch-btn">  
                                                </div>
                                                </div>
                                            </div>

                                   
                                   </div>
                                </div>
                                </div>
             

</div>
</div>
</div>
</div>
</section>     
</body>
</html>

DyspBackend/questions/templates/questions/form-template.html
{% for field in form %}
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small"> {{ field.errors }}</span>
    </div>
    <label class="control-label col-sm-2"> {{ field.label_tag }}
    </label>
    <div class="col-sm-10">{{ field }}</div>

</div>
{% endfor %}

DyspBackend/questions/templates/questions/qs.html
{% load staticfiles %}

{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    <title>Home | Dyspodium</title>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/all-themes.css' %}" rel="stylesheet" />
</head>
<body class="theme-red" style="background-color:#2E2E2E;">

    <div class="overlay"></div>
   <nav class="navbar" style="background-color:#04B486; color:#2E2E2E;">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="index.html"><b>DYSPODIUM</b></a>
            </div>
            <form class="navbar-form navbar-left" action="#" method="get" role="search">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search" name="q" value="">
                        <div class="input-group-btn">
                            <button class="btn btn-default glyphicon glyphicon-search" type="submit"></button>
                        </div>
                </div>
            </form>
            <div class="collapse navbar-collapse" id="navbar-collapse" style="background-color:#04B486; color:#2E2E2E;" >

                <ul class="nav navbar-nav navbar-right">
                   
                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Add Question</span>
                        </a>
                    </li>

                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-bell" aria-hidden="true"></span></span>
                        </a>
                    </li>
                   
                    
                    <li class="">
                        <a href="/account/settings">
                            <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></span>
                        </a>
                    </li>
                    
    
        <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span></span>
                        </a>
                    </li>
        <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span></span>
                        </a>
                    </li>

           
                    </ul>
            </div>
        </div>
    </nav>
    <section class="content" style="background-color:#2E2E2E; color:#04B486;">
        <div class="container-fluid">
            <div class="block-header">
                <h3>User Feed</h3>
            </div>
            <div class="row clearfix" >
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="card" style="background-color:#424242; color:#04B486;">
                        
                        <div class="header" style="background-color:##424242; color:#04B486;">

                            <div class="row clearfix">
                                <div class="col-xs-12 col-sm-6">
                                    <div class="user-info">
                                        <div class="col-md-3 image">
                                        <img src="{% static 'images/user.png' %}" width="40" height="40" alt="User" class="img-circle img-responsive" />
                                        <div>
                                   </div> 
                                 </div>
                                    
                                        <div class="info-container">
                                    <div class="name row clearfixl" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color:red"><h5> {{ q.creator }} :</h5><h5> {{q.question}} </h5></div>
                                    
                                </div>
                                        </div>
                                            <div class="col-xs-12 col-sm-6 align-right" >
                                                <div class="switch panel-switch-btn">  
                                                </div>
                                                </div>
                                            </div>

                                    <div align="right"><h6>Report</h6></div>
                                           <div align="right"><h6>Date</h6></div>
                                    
                                </div>
                                </div>
                                {% for i in q.answer_set.all %}
                                <div class="row clearfix">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

                    <div class="card">


                        <div class="header">

                            <div class="row clearfix">
                              
                                <div class="col-xs-12 col-sm-6">
                                
                                    <div class="user-info">

                                        <div class="col-md-3 image">
                                
                                        <img src="{% static 'images/user.png' %}" width="48" height="48" alt="User" class="img-circle img-responsive" />
                                        
                                 </div>

                                 <div class="info-container">

                <div class="name row clearfixl" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><h5> {{ i.user }} :</h5></div>
                <div><h5> {{i.answer}} </h5></div>
                                    
                                </div>
                            
                            </div>
            
                                <div class="col-xs-12 col-sm-6 align-right">

                                    <div class="switch panel-switch-btn">
                                        
                                    </div>
                                </div>
                            </div>
                            <div align="right"><h6>Report</h6></div>
                                           <div align="right"><h6>Date</h6></div>
            {% endfor %}
             
                    </div>
                    </div>
                    </div>
        </section>     
        </body>
</html>

DyspBackend/users/templates/users/us.html
{% load staticfiles %}
<h1> User Info!! </h1>
<h3>User : {{ u.first_name }}{{ u.last_name }}</h3>
<h2>{{u.bio}}</h2>
<img src="/Dyspodium/DyspBackend/users/static/images"> 